USE [master]
GO
/****** Object:  Database [DylanOchoaLibraryDB]    Script Date: 3/28/2021 8:30:45 PM ******/
CREATE DATABASE [DylanOchoaLibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DylanOchoaLibraryDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DylanOchoaLibraryDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DylanOchoaLibraryDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DylanOchoaLibraryDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DylanOchoaLibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET  MULTI_USER 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET  READ_WRITE 
GO
