USE [master]
GO
/****** Object:  Database [DylanOchoaLibraryDB]    Script Date: 5/23/2021 4:28:12 PM ******/
CREATE DATABASE [DylanOchoaLibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DylanOchoaLibraryDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DylanOchoaLibraryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DylanOchoaLibraryDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DylanOchoaLibraryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DylanOchoaLibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET RECOVERY FULL 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET  MULTI_USER 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DylanOchoaLibraryDB', N'ON'
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET QUERY_STORE = OFF
GO
ALTER DATABASE [DylanOchoaLibraryDB] SET  READ_WRITE 
GO
